"""empty message

Revision ID: 29a79558f1a1
Revises: 4871dfea231b
Create Date: 2021-01-03 16:38:26.402266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a79558f1a1'
down_revision = '4871dfea231b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_list', sa.Column('date', sa.TIMESTAMP(), nullable=True))
    op.add_column('board_list', sa.Column('name', sa.String(), nullable=True))
    op.add_column('board_list', sa.Column('text', sa.String(), nullable=True))
    op.add_column('board_list', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board_list', 'title')
    op.drop_column('board_list', 'text')
    op.drop_column('board_list', 'name')
    op.drop_column('board_list', 'date')
    # ### end Alembic commands ###
