"""empty message

Revision ID: 474ef6831082
Revises: 29a79558f1a1
Create Date: 2021-01-03 22:31:31.638855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474ef6831082'
down_revision = '29a79558f1a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_list', sa.Column('index', sa.Integer(), nullable=False))
    op.alter_column('board_list', 'board_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board_list', 'board_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('board_list', 'index')
    # ### end Alembic commands ###
