"""empty message

Revision ID: 4871dfea231b
Revises: 1cdc650159ca
Create Date: 2021-01-03 02:26:39.627384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4871dfea231b'
down_revision = '1cdc650159ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_list',
    sa.Column('board_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('board_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_list')
    # ### end Alembic commands ###
