"""empty message

Revision ID: 9017980f382a
Revises: e9c7a6bc2045
Create Date: 2021-01-05 02:00:13.419103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9017980f382a'
down_revision = 'e9c7a6bc2045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_list', sa.Column('group', sa.Integer(), autoincrement=True, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board_list', 'group')
    # ### end Alembic commands ###
