"""empty message

Revision ID: 940250f66ef7
Revises: 474ef6831082
Create Date: 2021-01-03 22:35:34.143256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940250f66ef7'
down_revision = '474ef6831082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_list',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('board_name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_list')
    # ### end Alembic commands ###
