"""empty message

Revision ID: 9f19769a81e5
Revises: 6735d80443ae
Create Date: 2021-01-02 18:30:27.056448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f19769a81e5'
down_revision = '6735d80443ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(), nullable=True))
    op.drop_column('user', 'model')
    op.drop_column('user', 'doors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('doors', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'password')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
