"""empty message

Revision ID: e3fdacbdb80a
Revises: 3d82ad78c407
Create Date: 2021-01-05 14:26:46.776972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3fdacbdb80a'
down_revision = '3d82ad78c407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_list', sa.Column('index', sa.Integer(), nullable=False))
    op.drop_column('board_list', 'indexs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_list', sa.Column('indexs', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('board_list', 'index')
    # ### end Alembic commands ###
