"""empty message

Revision ID: e9c7a6bc2045
Revises: e8ddc319b0a4
Create Date: 2021-01-04 14:20:39.878327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c7a6bc2045'
down_revision = 'e8ddc319b0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_list',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('board_name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_list')
    # ### end Alembic commands ###
